### PR TITLE
Set-up formatting CI/CD with husky and git hooks, and updated README with info

### PR DESCRIPTION
**Pull request by matthewcn56**
Set-up husky to auto-format all our files as a pre-commit git hook, and added a custom `yarn format` script, and updated our README for how to get set-up with our dev-dependencies.

### CODE REVIEW

**Review by dtjanaka — APPROVED** [review]
LGTM!

**Comment by dtjanaka** [comment]
Note to self: https://www.linkedin.com/pulse/wsl-bash-script-binshm-bad-interpreter-file-directory-john-west

**Comment by matthewcn56** [comment]
> Note to self: https://www.linkedin.com/pulse/wsl-bash-script-binshm-bad-interpreter-file-directory-john-west

o did you have to do anything special to get the bash scripts in the git hook to work properly on wsl

**Comment by matthewcn56** [comment]
cuz the new teachLA projects use husky and I don't think people have run into issues with it yet

**Comment by matthewcn56** [comment]
oh wait actually they added some extra stuff at the base of all of their hooks

```sh
command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Windows 10, Git Bash and Yarn workaround
if command_exists winpty && test -t 1; then
  exec < /dev/tty
fi
```
maybe that fixes it? @dtjanaka

**Pull request merged**
